version: '2'

services:

  package36:
    image: difu/matplotliblambda
    command: sh "create_deployment.sh"
    working_dir: /deployment
    volumes:
      - './lambda:/lambda'
      - './:/export'
